return {
--  "mfussenegger/nvim-dap",
--  dependencies = {
--    "nvim-neotest/nvim-nio",
--    "rcarriga/nvim-dap-ui"
--  },
--  config = function()
--    local dap = require("dap")
--    local dapui = require("dapui")
--    dap.adapters.gdb = {
--      type = 'executable',
--      command = 'gdb',
--      name = 'gdb'
--    }
--    --dap.configurations.cpp = {
--      
--    --}
--    dap.listeners.before.attach.dapui_config = function()
--      dapui.open()
--    end
--    dap.listeners.before.launch.dapui_config = function()
--      dapui.open()
--    end
--    dap.listeners.before.event_terminated.dapui_config = function()
--      dapui.open()
--    end
--    dap.listeners.before.even_exited.dapui_config = function()
--      dapui.open()
--    end
--    vim.keymap.set("n", "<leader>db", dap.toggle_breakpoint, {})
--    vim.keymap.set("n", "<leader>dd", dap.continue, {})
--  end
}

